CREATE TABLE page
(
    name VARCHAR(100)NULL DEFAULT NULL,
    mid INT(11)NULL DEFAULT NULL,
    bvid VARCHAR(100)NULL DEFAULT NULL,
    cid BIGINT(20)NOT NULL COMMENT '主键ID',
    url VARCHAR(100)NULL DEFAULT NULL,
    page INT(11)NULL DEFAULT NULL,
    view INT(11)NULL DEFAULT NULL,
    duration INT(11)NULL DEFAULT NULL,
    part VARCHAR(100)NULL DEFAULT NULL,
    PRIMARY KEY (cid)
);